apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-clean-backups
  namespace: mo-job
spec:
  schedule: "0 4 * * *" # change me
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 20
  failedJobsHistoryLimit: 20
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-clean-backups
            image: mo_ctl_standalone:latest # change me
            imagePullPolicy: IfNotPresent
            args:
            - "clean_backup"
            env:
            - name: _CTL_S3_CLIENT
              value: "/usr/local/bin/mc"
            - name: _CTL_S3_API_VERSION
              value: "S3v4"
            - name: _CTL_S3_CONFIG_DIR
              value: "/tmp/s3_config"
            - name: _CTL_BACKUP_PHYSICAL_TYPE
              value: "s3"
            - name: _CTL_BACKUP_S3_ENDPOINT
              value: "http://minio.minio-tenant.svc.cluster.local" # change me
            - name: _CTL_BACKUP_S3_BUCKET
              value: "matrix-qa"
            - name: _CTL_BACKUP_DATA_PATH
              value: "/mo-backup"
            - name: _CTL_TOOL_LOG_PATH
              value: /data/logs/mo_ctl

            # s3 credentials
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3key
                  key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
            - name: backup-metadata
              mountPath: /data/logs/mo_ctl
            - name: tmp-config-dir
              mountPath: /tmp/s3_config
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "200m"
          volumes:
          - name: backup-metadata
            persistentVolumeClaim:
              claimName: backup-metadata-pvc
          - name: tmp-config-dir
            emptyDir: {}
          restartPolicy: OnFailure
