apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-clean-logs
  namespace: mo-job
spec:
  schedule: "0 3 * * *" # change me
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 20
  failedJobsHistoryLimit: 20
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-clean-logs
            image: mo-ctl:latest # change me
            imagePullPolicy: IfNotPresent
            args:
            - "clean_logs"
            env:
            # connection info 
            - name: _CTL_MO_HOST
              value: "mo-proxy.mo-db.svc.cluster.local" # change me
            - name: _CTL_MO_PORT
              value: "6001"
            - name: _CTL_MO_USER
              value: "dump"
            - name: _CTL_MO_PW
              value: "111"
            - name: _CTL_CLEAN_LOGS_DAYS_BEFORE
              value: "7"
              
            - name: _CTL_CTL_LOG_DIR
              value: "/data/logs/mo_ctl/logs"
            volumeMounts:
            - name: backup-metadata
              mountPath: /data/logs/mo_ctl
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "200m"
          volumes:
          - name: backup-metadata
            persistentVolumeClaim:
              claimName: backup-metadata-pvc
          restartPolicy: OnFailure
