name: Build EKS Runner Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build Image and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Image Tags
        id: prepare
        run: |
          tags="registry.cn-hangzhou.aliyuncs.com/mocloud/mo_ctl_standard:commit-${{ github.sha }}";
          echo "tags=${tags}" >> $GITHUB_OUTPUT;
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: "registry.cn-hangzhou.aliyuncs.com"
          username: ${{ secrets.ACR_CI_USERNAME }}
          password: ${{ secrets.ACR_CI_TOKEN }}
      - name: Build and Push Image
        uses: ./.github/actions/image-build
        with:
          tags: ${{ steps.prepare.outputs.tags }}
          file-path: ${{ github.workspace }}/optools/image/Dockerfile
          context: ${{ github.workspace }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.TOKEN_ACTION }}
