name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install shfmt and Lint
        run: |
          make shfmt-install
          make shfmt
      - name: Check Lint Result
        run: |
          changes=$(git status --porcelain)
          if [ -n "$changes" ]; then
            echo "Lint check failed, unformatted files:"
            echo "--------------------------------------------------"
            echo "$changes"
            echo "--------------------------------------------------"
            exit 1
          else
            echo "Lint check passed"
          fi
